CREATE TABLE vehicles(
vehicle_id	INT IDENTITY(1,1)	NOT NULL
,plate_no	NVARCHAR(100)	NULL
,conduction_no	NVARCHAR(100)	NULL
,chassis_no	NVARCHAR(100)	NULL
,engine_no	NVARCHAR(100)	NULL
,date_acquired	DATE	NULL
,exp_registration_date	DATE	NULL
,exp_insurance_date	DATE	NULL
,vehicle_maker_id	INT	NULL
,odometer_reading	INT	NULL
,is_active	CHAR(1)	NULL
,status_id	INT	NULL
,hash_key	NTEXT(2147483646)	NULL
,client_id	INT	NULL
,created_by	INT	NULL
,created_date	DATETIME	NULL
,updated_by	INT	NULL
,updated_date	DATETIME	NULL)